### ISSUE TITLE
 [feature]: Add tick mark box for each task

### ISSUE THREAD

**Issue by tarun8989096553** [tarunkumarkale/react-to-do-list#2]
### Description
This feature introduces a new task completion indicator to the to-do list application. Users can now see a checkbox next to each task item, allowing them to mark tasks as completed with a simple click. This enhancement provides users with a visual way to track their progress and easily identify which tasks they have completed.

### Implementation Details
- Added a new checkbox component to the task item UI.
- Implemented state management logic to toggle the completion status of tasks.
- Updated the task item rendering logic to display the checkbox and handle user interactions.
- Utilized React hooks for managing state and handling user events.

**Comment by tarunkumarkale** [comment]
"Thank you for telling me.
